# Generated by Django 4.0.5 on 2022-06-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booking_date', 'booking_time']},
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(default='Gareth', max_length=25),
            preserve_default=False,
        ),
    ]
