# Generated by Django 4.0.5 on 2022-06-21 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('desert', 'Desert'), ('drink', 'Drink'), ('side', 'Side')], default='starter', max_length=25)),
                ('description', models.TextField(default='')),
                ('price', models.FloatField(default=0.0)),
                ('contains_nuts', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL)),
                ('deserts', models.ManyToManyField(related_name='deserts', to='menu.menuitem')),
                ('drinks', models.ManyToManyField(related_name='drinks', to='menu.menuitem')),
                ('mains', models.ManyToManyField(related_name='mains', to='menu.menuitem')),
                ('sides', models.ManyToManyField(related_name='sides', to='menu.menuitem')),
                ('starters', models.ManyToManyField(related_name='starters', to='menu.menuitem')),
            ],
            options={
                'ordering': ['-active', 'name'],
            },
        ),
    ]
