# Generated by Django 4.0.5 on 2022-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_name', models.CharField(max_length=25)),
                ('menu_item_type', models.CharField(choices=[('Starter', 'starter'), ('Main', 'main'), ('Desert', 'desert'), ('Drink', 'drink'), ('Side', 'side')], default='starter', max_length=25)),
                ('menu_item_price', models.FloatField()),
            ],
            options={
                'ordering': ['menu_item_name'],
            },
        ),
    ]
