# Generated by Django 4.0.5 on 2022-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
