# Generated by Django 4.0.5 on 2022-06-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_contains_nuts_menuitem_vegan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=25)),
                ('menu_items', models.ManyToManyField(related_name='menus', to='menu.menuitem')),
            ],
            options={
                'ordering': ['menu_name'],
            },
        ),
    ]
