# Generated by Django 4.0.5 on 2022-06-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_gluten_free_alter_menuitem_menu_item_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['menu_item_type', 'menu_item_name']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_item_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_item_name',
            field=models.CharField(max_length=50),
        ),
    ]
