# Generated by Django 4.0.5 on 2022-06-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_active',
            field=models.BooleanField(default=False),
        ),
    ]
