# Generated by Django 4.0.5 on 2022-06-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu_menu_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-menu_item_type', 'menu_item_name']},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_item_price',
            field=models.FloatField(default=0.0),
        ),
    ]
