# Generated by Django 4.0.5 on 2022-06-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-menu_active', 'menu_name']},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_items_mains',
            field=models.ManyToManyField(related_name='items_mains', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_items_starters',
            field=models.ManyToManyField(related_name='items_starters', to='menu.menuitem'),
        ),
    ]
