# Generated by Django 4.0.5 on 2022-06-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menu_options_remove_menu_menu_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_items_deserts',
            field=models.ManyToManyField(related_name='items_deserts', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_items_drinks',
            field=models.ManyToManyField(related_name='items_drinks', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_items_sides',
            field=models.ManyToManyField(related_name='items_sides', to='menu.menuitem'),
        ),
    ]
